python main.py --dataset chaii \
--langs hi ta bn^ mr^ \
--min_langs 1 \
--max_steps 5000 \
--logging_steps 100 \
--eval_steps 100 \
--save_steps 100 \
--train_batch_size 16 \
--gradient_accumulation_steps 1 \
--eval_batch_size 16 \
--model_name xlmroberta-squad \
--eval False