wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    code_path: code/main.py
    framework: huggingface
    huggingface_version: 4.16.2
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.9.7
    start_time: 1645186847
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      4: 3.9.7
      5: 0.12.10
      6: 4.16.2
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 4
dataset:
  desc: null
  value: chaii
doc_stride:
  desc: null
  value: 128
eval:
  desc: null
  value: true
gradient_accumulation_steps:
  desc: null
  value: 8
langs:
  desc: null
  value:
  - hi
  - ta
lr:
  desc: null
  value: 3.0e-06
max_length:
  desc: null
  value: 384
model_ckpt:
  desc: null
  value: bert-base-multilingual-cased
num_epochs:
  desc: null
  value: 2
warmup_ratio:
  desc: null
  value: 0.1
weight_decay:
  desc: null
  value: 0.01
